### ISSUE TITLE
Other Download Options

### ISSUE THREAD

**Issue by cheese529** [davidkeipert/tikfav#2]
Would it be possible to use this script to download other things from our user data as well, such as favorited tiktok sounds, video share history and liked videos? 
Also would it ever be possible to use this script to download all the videos that another user has posted, I know you can use something like a chrome extension called link gopher to extract all the URLs of the videos posted on a tiktok page into a text file so maybe we could make something work with that?

**Comment by davidkeipert** [comment]
Downloading liked videos and favorite sounds is already a work-in-progress, I just haven't pushed the new branch yet. Hoping to get it done this week. 

Downloading another user's posts is kind out of scope for this app right now bc it's hard coded to extract data from the JSON file generated by tiktok, but once I release the other features I'll look into options for reading from a user generated file. I think there are also API endpoints that return a list of a user's posts, but it might have some limitations.

**Comment by davidkeipert** [comment]
Leaving this issue open till I add share history and sounds download options.

**Comment by davidkeipert** [comment]
leaving this open till I add options to download sounds and share history.

**Comment by cheese529** [comment]
Thank you so much for adding that liked videos feature! it is truly a game changer. you have no idea how much I appreciate this, i'm sure so many others will be grateful for it too. hopefully you're able to add the sounds and share history as well whenever you get the time. 

Now regarding downloading another users posts, let me know if you need any ideas. Like a mentioned before, it is possible to scrape all the video URLs posted by a user just by scrolling all the way to the bottom of the profile in a web browser, so maybe we can then convert that text file into JSON?

**Comment by ismailnoor819** [comment]
Hi, just wanna thank you for doing this as TikTok is being banned in my country at the moment so this is perfect. Do you have any ETA on how much longer it would take to implement downloading favourited sounds and share history. I’d like to get this stuff downloaded ASAP since my of my followed users are deleting their accounts or being banned.

Also would you be so kind enough to also add the ability to download my watch history and direct messages categories as well? It would be super nice to download both all of the TikTok’s that were shared with me in direct messages and then TikToks that I sent myself.

**Comment by davidkeipert** [comment]
I'll finish those features and release an update later today. Watch history should be trivial to add, I'll add that to this release too. 



> Also would you be so kind enough to also add the ability to download my watch history and direct messages categories as well? It would be super nice to download both all of the TikTok’s that were shared with me in direct messages and then TikToks that I sent myself.

I don't have any videos shared through DM's in my current user file, so that might be difficult to work on right away. Would you be able to post a snippet of JSON from your file with a direct message item you want to be able to download? If you don't want to post it publicly, you can send it to the email address on my profile. If that's not an option, it might take a bit longer to develop while I wait for a new data download for my account.

**Comment by davidkeipert** [comment]
Closing this issue as the main download features have been added. I'll keep working on the other suggestions. 

Feel free to open a new issue for discussion about other features like custom video lists or other download categories.

**Comment by ismailnoor819** [comment]
I sent you an email.

**Comment by ismailnoor819** [comment]
> I'll finish those features and release an update later today. Watch history should be trivial to add, I'll add that to this release too. 
> 
> 
> 
> 
> 
> 
> 
> > Also would you be so kind enough to also add the ability to download my watch history and direct messages categories as well? It would be super nice to download both all of the TikTok’s that were shared with me in direct messages and then TikToks that I sent myself.
> 
> 
> 
> I don't have any videos shared through DM's in my current user file, so that might be difficult to work on right away. Would you be able to post a snippet of JSON from your file with a direct message item you want to be able to download? If you don't want to post it publicly, you can send it to the email address on my profile. If that's not an option, it might take a bit longer to develop while I wait for a new data download for my account. 
> 
> 

Sent you an email.
